name: AdditionalWeaponry

author: ExistingEevee

description: Additional weaponry for your slimefun adventures

## CHANGE this to the path of the class that extends JavaPlugin.
main: com.existingeevee.additionalweaponry.AdditionalWeaponry

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14
